[versions]
netmonitor = "1.1.0" # https://github.com/Cach30verfl0w/netmonitor-kmp/releases
kotlin = "2.4.0" # https://github.com/JetBrains/kotlin/releases
jvmTarget = "21"

comInterop = "1.2.1" # https://github.com/karmakrafts/COMInterop/releases
kotlinx-coroutines = "1.11.0" # https://github.com/Kotlin/kotlinx.coroutines/releases
composeMultiplatform = "1.11.1" # https://github.com/JetBrains/compose-multiplatform/releases
mavenPublish = "0.37.0" # https://github.com/vanniktech/gradle-maven-publish-plugin/releases

# Android
androidGradle = "9.2.1" # https://mvnrepository.com/artifact/com.android.tools.build/gradle
android-compileSdk = "36"
android-targetSdk = "36"
android-minSdk = "23"

# Example App
material3 = "1.11.0-alpha07" # https://github.com/JetBrains/compose-multiplatform/releases
androidx-activity = "1.13.0" # https://developer.android.com/jetpack/androidx/releases/activity

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
compose-runtime-annotations = { group = "androidx.compose.runtime", name = "runtime-annotation", version.ref = "composeMultiplatform" }
comInterop-core = { group = "dev.karmakrafts.cominterop", name = "cominterop-core", version.ref = "comInterop" }

# Example App
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "composeMultiplatform" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "composeMultiplatform" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "composeMultiplatform" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }

[plugins]

kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradle" }
androidApplication = { id = "com.android.application", version.ref = "androidGradle" }

# Compose
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }